import { z } from 'zod';
import { SENSORY_AXES } from '../constants/sensory-axes';
import {
  CONCENTRATION, GENDER_TARGET, OLFACTIVE_FAMILY,
  LAYER_ROLE, REFORMULATION_RISK, PRICE_TIER
} from '../constants/vocabularies';
import { OCCASION_FIELDS } from '../constants/occasions';

// Sensory axes as optional float fields (0-10)
const sensoryFields = Object.fromEntries(
  SENSORY_AXES.map(axis => [`sensory_${axis}`, z.number().min(0).max(10).optional()])
);

// Occasion scores as optional float fields (0-10)
const occasionFields = Object.fromEntries(
  OCCASION_FIELDS.map(occ => [`occasion_${occ}`, z.number().min(0).max(10).optional()])
);

export const NoteSchema = z.object({
  name: z.string(),
  position: z.enum(['top', 'heart', 'base']).optional(),
  intensity: z.number().min(0).max(10).optional(),
  is_synthetic: z.boolean().optional(),
});

export const PerfumeSchema = z.object({
  // Identity
  name: z.string().min(1),
  brand_id: z.string().uuid().optional(),
  brand_name: z.string().optional(), // for pipeline use before brand resolution
  perfumer_ids: z.array(z.string().uuid()).optional(),
  year_released: z.number().int().min(1800).max(2030).optional(),
  concentration: z.enum(CONCENTRATION).optional(),
  gender_target: z.enum(GENDER_TARGET).optional(),
  discontinued: z.boolean().default(false),
  price_usd: z.number().positive().optional(),
  price_tier: z.enum(PRICE_TIER).optional(),

  // Classification
  olfactive_family: z.enum(OLFACTIVE_FAMILY).optional(),
  olfactive_subfamilies: z.array(z.string()).optional(),
  notes_top: z.array(NoteSchema).optional(),
  notes_heart: z.array(NoteSchema).optional(),
  notes_base: z.array(NoteSchema).optional(),
  key_accords: z.array(z.string()).optional(),

  // Sensory axes (generated by AI enricher)
  ...sensoryFields,

  // Occasion scores (generated by AI enricher)
  ...occasionFields,

  // Community scores
  community_rating: z.number().min(0).max(5).optional(),
  rating_count: z.number().int().optional(),
  compliment_getter: z.number().min(0).max(10).optional(),
  blind_buy_safe: z.number().min(0).max(10).optional(),
  value_for_money: z.number().min(0).max(10).optional(),
  longevity_score: z.number().min(0).max(10).optional(),
  sillage_score: z.number().min(0).max(10).optional(),

  // Arrays
  declared_allergens: z.array(z.string()).optional(),
  mood_tags: z.array(z.string()).optional(),
  aesthetic_tags: z.array(z.string()).optional(),
  key_molecules: z.array(z.string()).optional(),
  praised_for: z.array(z.string()).optional(),
  criticized_for: z.array(z.string()).optional(),
  evokes: z.array(z.string()).optional(),
  layer_role: z.array(z.enum(LAYER_ROLE)).optional(),

  // Safety
  vegan: z.boolean().optional(),
  cruelty_free: z.boolean().optional(),
  reformulation_risk: z.enum(REFORMULATION_RISK).optional(),

  // JSONB fields (complex nested objects, always read whole)
  evolution_profile: z.record(z.unknown()).optional(),
  projection_arc: z.record(z.unknown()).optional(),
  layering: z.record(z.unknown()).optional(),
  bottle_design: z.record(z.unknown()).optional(),
  reformulation_history: z.record(z.unknown()).optional(),
  wardrobe_role: z.record(z.unknown()).optional(),
  skin_behavior: z.record(z.unknown()).optional(),
  fragrance_dna: z.record(z.unknown()).optional(),

  // Metadata
  source_url: z.string().url().optional(),
  source_name: z.string().optional(),
  data_completeness: z.number().min(0).max(100).optional(),
});

export type Perfume = z.infer<typeof PerfumeSchema>;
export type PerfumeInput = z.input<typeof PerfumeSchema>;
